language: java
jdk: oraclejdk8

services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS fridget_test;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('n0password') where User='testuser'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart

script:
  - ./test.sh
  - ./gradlew check
